### ISSUE TITLE
Can't find source path :/.flatpak-builder/rofiles/rofiles-nFpUXA/var/lib: Permission denied

### ISSUE THREAD

**Issue by wada3n** [AparokshaUI/AdwaitaTemplate#1]
Hi,
When I try to build with: 

> sudo flatpak-builder build-dir org.freedesktop.Sdk.Extension.swift.json --install --force-clean

This error appears to me, I do not clearly understand where the problem lies

> mptying app dir 'build-dir'
Downloading sources
Fetching full git repo https://github.com/JohnSundell/CollectionConcurrencyKit.git
Fetching full git repo https://github.com/krzyzanowskim/CryptoSwift.git
Fetching full git repo https://github.com/jpsim/SourceKitten.git
Fetching full git repo https://github.com/apple/swift-argument-parser.git
Fetching full git repo https://github.com/apple/swift-syntax.git
Fetching full git repo https://github.com/scottrhoyt/SwiftyTextTable.git
Fetching full git repo https://github.com/drmohundro/SWXMLHash.git
Fetching full git repo https://github.com/jpsim/Yams.git
Starting build of org.freedesktop.Sdk.Extension.swift
Cache miss, checking out last cache hit
========================================================================
Building module libedit in ~/swift-main/.flatpak-builder/build/libedit-1
========================================================================
bwrap: Can't find source path ~/swift-main/.flatpak-builder/rofiles/rofiles-nFpUXA/var/lib: Permission denied
Error: module libedit: Le processus fils s’est terminé avec le code 1

---------------
Fedora: 39
Gnome: 45.3

**Comment by david-swift** [comment]
Hi @wada3n

I have experienced a similar problem on Fedora:
```
bwrap: Can't find source path $XDG_RUNTIME_DIR/doc/by-app/com.obsproject.Studio: Permission denied
```

I was able to solve it using an answer I found in [this forum](https://forums.gentoo.org/viewtopic-p-8685542.html?sid=37a2dde71e35041bb19c0974251afe34):
```
chmod u+s /usr/bin/bwrap
```

Maybe that helps?

**Comment by wada3n** [comment]
Hi @david-swift ,

Thank you so much for your help, it's working now..

I also wanted to take a moment to congratulate you on your amazing work on the Swift on Adwaita . It's a truly impressive feat and I'm excited to see what the future holds for this project.

Your work is making it possible for more developers to use Swift to build beautiful and functional apps. I'm sure this project will have a positive impact on the GNOME community for years to come.

Thanks again for your help and support. I really appreciate it.

**Comment by david-swift** [comment]
Happy it works now! I'm going to add it to the README.

And thank you so much for the kind words!
