### ISSUE TITLE
Unable to install Swift Sdk extension

### ISSUE THREAD

**Issue by kdwk** [AparokshaUI/AdwaitaTemplate#2]
The Sdk extension repo doesn't seem to have Issues so I filed it here.

When running `sudo flatpak-builder build-dir org.freedesktop.Sdk.Extension.swift.json --install --force-clean` in the downloaded folder, the following error happens: 
`bwrap: Can't find source path /var/home/kdwk/Projects/org.freedesktop.Sdk.Extension.swift-main/.flatpak-builder/rofiles/rofiles-hG49ny/var/lib: Permission denied
Error: module libedit: Child process exited with code 1
`

And therefore the Sdk extension cannot be installed.

**Comment by david-swift** [comment]
Have you tried executing the following command? It seems to be the same error as in #1.

```
chmod u+s /usr/bin/bwrap
```

**Comment by kdwk** [comment]
Unfortunately now it fails with

`Please review the exported files and the metadata
Committing stage finish to cache
Exporting org.freedesktop.Sdk.Extension.swift to repo
Commit: 050f1e2af0697722e2fd5f0f02c718f4cd029d054162e14b09f65413d8f0de9b
Metadata Total: 237
Metadata Written: 2
Content Total: 1095
Content Written: 0
Content Bytes Written: 0 (0 bytes)
error: open(O_TMPFILE): Permission denied
Install failed: Child process exited with code 1
`

**Comment by david-swift** [comment]
Are you installing it using the following command?

```
sudo flatpak-builder build-dir org.freedesktop.Sdk.Extension.swift.json --install --force-clean
```

**Comment by kdwk** [comment]
Yes. That's the same command

**Comment by kdwk** [comment]
![Screenshot from 2024-02-10 14-56-09](https://github.com/AparokshaUI/AdwaitaTemplate/assets/39268094/318fb5d1-1d0f-4bf6-b37b-16b59e89e6e0)

The build-dir folder doesn't seem to allow any other user than "user #524288" to create files

**Comment by david-swift** [comment]
Strange, the super user should have the permission.

![image](https://github.com/AparokshaUI/AdwaitaTemplate/assets/106754840/437d69c9-fa63-45af-81bf-40d329f0dfca)

**Comment by david-swift** [comment]
I found this comment, maybe that helps?

https://github.com/flatpak/flatpak/issues/1507#issuecomment-378024458

**Comment by kdwk** [comment]
> I found this comment, maybe that helps?
> 
> [flatpak/flatpak#1507 (comment)](https://github.com/flatpak/flatpak/issues/1507#issuecomment-378024458)

This doesn't work because /var/lib is not mutable on my system

**Comment by kdwk** [comment]
![Screenshot from 2024-02-10 15-07-24](https://github.com/AparokshaUI/AdwaitaTemplate/assets/39268094/364d5ef6-ce3b-46d8-89ee-7ecd38cedf0c)

Hmm, it still fails after I gave everyone write access to build-dir

**Comment by david-swift** [comment]
I think that is because the build-dir gets deleted and created again when running the installation command, so the permissions reset.

**Comment by david-swift** [comment]
Have you tried running `flatpak repair`? Or installing only for the user by appending the `--user` flag? I have no idea whether that helps, but it might be worth trying.

**Comment by kdwk** [comment]
I did `--user` and it worked. Thanks

**Comment by david-swift** [comment]
I've just added instructions to the README. Thanks for opening the issue!
