### ISSUE TITLE
Gnome Builder cannot find the installed Swift SDK extension

### ISSUE THREAD

**Issue by kdwk** [AparokshaUI/AdwaitaTemplate#3]
After installing the Swift SDK extension (with  `--user`), and trying to run the AdwaitaTemplate demo app in Gnome Builder, the build output says 
`error: Requested extension org.freedesktop.Sdk.Extension.swift/x86_64/45 not installed
Error: Child process exited with code 1
`

**Comment by kdwk** [comment]
It seems the installed SDK extension is `23.08` but Builder wants `45`

**Comment by david-swift** [comment]
Very strange! The GNOME runtime version 45 is built on top of Freedesktop 23.08, so it should actually search for org.freedesktop.Sdk.Extension.swift/x86_64/23.08 (and it does also on my device). Maybe it really is a GNOME Builder problem, have you tried restarting?

**Comment by kdwk** [comment]
The Builder people say the error message is incorrect, and that even if it says it can't find `45` what it really means is it can't find `23.08`. So apparently Builder cannot see `23.08` even though I installed it

**Comment by kdwk** [comment]
![Screenshot from 2024-02-10 18-50-07](https://github.com/AparokshaUI/AdwaitaTemplate/assets/39268094/69c01eb0-d0f6-48dc-b006-6e3ca67d1483)

Hmm looks like the Sdk extension is not actually installed even if it says it is

**Comment by david-swift** [comment]
I removed and installed again the SDK extension on my device, also with `--user`, and it succeeded. This problem is so strange! I don't have a deep understanding of Flatpak, so I can't help unfortunately. Do other SDK extensions work? Maybe you can try installing it from Flathub once it gets accepted (see progress [here](https://github.com/flathub/flathub/pull/4935)).

**Comment by kdwk** [comment]
I installed the one from https://github.com/flathub/flathub/pull/4935#issuecomment-1937062369 and now it works fine

**Comment by david-swift** [comment]
Nice! There will be a change in the final version: It will include the major version in its name, so instead of `org.freedesktop.Sdk.Extension.swift`, it will be `org.freedesktop.Sdk.Extension.swift5`. I'll update this repo as soon as it is published.
