### ISSUE TITLE
No autocomplete or go to definition in GNOME Builder

### ISSUE THREAD

**Issue by Jimmy-Prime** [AparokshaUI/AdwaitaTemplate#4]
Hi, I am using GNOME Builder to build the template project, it works perfectly.
But when I try to edit the content, autocomplete or go to definition does not work.
How do I setup these functionalities in GNOME Builder? Or if it's not possible, any recommended editor?

**Comment by david-swift** [comment]
Hi! [This discussion](https://github.com/AparokshaUI/adwaita-swift/discussions/9) might be interesting for you. GNOME Builder's autocompletion works very well for me but it doesn't for everyone (also it didn't work immediately for me, only after working on a project for some time). An alternative is VS Code with the Flatpak extension (see discussion). Hope that helps?

**Comment by david-swift** [comment]
This has been fixed in the latest version of the template (more information: https://github.com/AparokshaUI/adwaita-swift/discussions/30).
