### ISSUE TITLE
Question: Build on / for Windows?

### ISSUE THREAD

**Issue by florian-obernberger** [AparokshaUI/AdwaitaTemplate#6]
Hey there, I was wondering if it would also be possible to build an application with this for Windows? It _should_ be possible, since Swift for Windows exist and adwaita should also work on Windows. But I am not entirely sure how to tackle this, so that's why I am asking here :)

**Comment by david-swift** [comment]
Sorry for ignoring your issue for so long (forgot about it): you can find useful information in https://github.com/AparokshaUI/adwaita-swift/issues/26. After making the Localized package work on Windows, a next step would be instructions: https://github.com/AparokshaUI/adwaita-swift/issues/13.

**Comment by david-swift** [comment]
Duplicate of https://github.com/AparokshaUI/adwaita-swift/issues/26
